django_bank/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import (
    registration_viev,
    logout_viev,
    login_viev,
    account_viev,
    change_password,
)

from transactions.views import (
    transactions_viev,
    transactions_inspection_viev,
)

from exchange.views import (
    exchange_viev,
    remove_lising_viev,
    exchange_money_viev,
)

from admindashboard.views import (
    admindashboard_viev,
    admindashboard_inspection_viev,
    admindashboard_mark_transaction,
)
from transaction_order.views import (
    transaction_order_viev,
    remove_transaction_order_viev,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("main.urls")),
    path('register/', registration_viev, name="register"),
    path('logout/', logout_viev, name="logout"),
    path('login/', login_viev, name="login"),

    path('account/', account_viev, name="account"),
    path('account/change_password', change_password, name="change_password"),

    path('saldo/', transactions_viev, name="transactions"),
    path('saldo/<int:id>', transactions_inspection_viev, name="inspect-transaction"),

    path('wymiana_walut/', exchange_viev, name="exchange"),
    path('removelisting/<int:id>', remove_lising_viev, name="remove-listing"),
    path('wymiana_walut/<int:id>', exchange_money_viev, name="exchange-money"),
    
    path('admindashboard/', admindashboard_viev, name="admindashboard"),
    path('admindashboard/inspect/<int:id>', admindashboard_inspection_viev, name="admin-inspect-transaction"),
    path('admindashboard/mark/<int:id>', admindashboard_mark_transaction, name="admin-mark-transaction"),

    path('zlecenia_transakcji/', transaction_order_viev, name="zlecenia_transakcji"),
    path('zlecenia_transakcji/<int:id>', remove_transaction_order_viev, name="remove_zlecenia_transakcji"),
    
    path('api/', include('transactions_api.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home")
]

transactions/models.py
from django.db import models
from account.models import Account

class Transaction(models.Model):
    WALUTY = (
        ('CNY', 'Yuan'),
        ('RUB', 'Rubel'),
        ('LIR', 'Lira'),
        ('CLP', 'Peso chilijskie'),
    )

    transaction_id      = models.BigAutoField(verbose_name="Id Tranzakcji", primary_key=True)
    sender_id           = models.ForeignKey(Account, blank=True, null=True, on_delete=models.SET_NULL, related_name='Nadawca', verbose_name="Nadawca")
    reciver_id          = models.ForeignKey(Account, null=True, on_delete=models.SET_NULL, related_name='Odbiorca', verbose_name="Odbiorca")
    kwota               = models.PositiveIntegerField(verbose_name="Kwota", blank=False, default=0)
    waluta              = models.CharField(verbose_name="Waluta", max_length=32, unique=False, choices=WALUTY)
    data_transakcji     = models.DateTimeField(verbose_name='Data Transakcji', auto_now_add=True)
    typ                 = models.PositiveIntegerField(verbose_name="Typ transakcji", default=0)
    # 0 - Przelew Zwykły
    # 1 - Wpłata na konto
    # 2 - Wypłata z konta
    # 3 - Wymiana walut
    title               = models.CharField(verbose_name="Tytuł przelewu", max_length=100, unique=False, default="Tytuł Przelewu")
    status              = models.PositiveIntegerField(verbose_name="Status transakcji", default=0)
    def __str__(self):
        return str(self.transaction_id)

transactions/forms.py
from django import forms
from transactions.models import Transaction
from account.models import Account
from django.utils.translation import gettext as _



class NewTransaction(forms.ModelForm):
    
    class Meta:
            model = Transaction
            fields = ['title', 'reciver_id', 'kwota', 'waluta']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['reciver_id'].label = "Nazwa odbiorcy"
        self.fields['reciver_id'].queryset = Account.objects.none()

        if 'reciver_id' in self.data:
            self.fields['reciver_id'].queryset = Account.objects.all()

        elif self.instance.pk:
            self.fields['reciver_id'].queryset = Account.objects.all().filter(pk=self.instance.reciver_id.pk)


class Withdraw(forms.ModelForm):
    title = forms.CharField(max_length=100, required=True, help_text="Wprowadź nick z serwera na jaki mają zostać wypłacone środki", label=_("Nazwa użytkownika"), widget=forms.TextInput(attrs={'placeholder': 'Wprowadz nazwe użytkownika'}))

    class Meta:
            model = Transaction
            fields = ['title', 'kwota', 'waluta']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['waluta'].widget.attrs['id'] = 'id_waluta2'

transactions/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from account.models import Account
from django.db.models import Q

from transactions.models import Transaction
from transactions.forms import NewTransaction, Withdraw
from transactions.filters import TransacionFilter

from exchange.models import ExchangeListing

from django.contrib import messages


def transactions_viev(request):
    

    if not request.user.is_authenticated:
        return redirect("login")

    sent_transactions = Transaction.objects.filter(Q(sender_id  = request.user.id) | Q(reciver_id = request.user.id)).order_by('-data_transakcji')
    transactions_filter = TransacionFilter(request.GET, queryset=sent_transactions)
    sent_transactions = transactions_filter
    

    form = NewTransaction(auto_id="NewTransaction_%s")
    withdraw_form = Withdraw()
    context = {
            'sent_transactions' : sent_transactions,
            'transaction_form' : form,
            'withdraw_form' : withdraw_form,
            'transactions_filter' : transactions_filter,
        }
    
    # Formularz przelewu wyszukiwanie konta 
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    if is_ajax:
        term = request.GET['q']
        reciver_id = Account.objects.all().filter(username__icontains=term)
        return JsonResponse(list(reciver_id.values()), safe=False)    

    # Przelewy
    if request.POST and 'transaction' in request.POST:
        form = NewTransaction(request.POST)
        if form.is_valid():
            trans   = form.save(commit=False)
            trans.sender_id = request.user

            sender = Account.objects.get(id=request.user.id)
            reciver = Account.objects.get(id=trans.reciver_id.id)

            if sender == reciver:
                messages.info(request, 'Nie możesz wysłać przelewu do samego siebie.')
            else:
                if trans.kwota == 0:
                    messages.info(request, 'Kwota przelewu musi być większa niż 0')
                else:
                    if getattr(sender, trans.waluta.lower()) - trans.kwota >= 0:
                        setattr(sender, trans.waluta.lower(), getattr(sender, trans.waluta.lower()) - trans.kwota)
                        setattr(reciver, trans.waluta.lower(), getattr(reciver, trans.waluta.lower()) + trans.kwota)
                        sender.save()
                        reciver.save() 
                        trans = trans.save()
                        return redirect('transactions')
                    else:
                        messages.info(request, 'Brak wystarczajacej liczby środków.')
 
                            

    # Wypłacanie  
    elif request.POST and 'withdraw' in request.POST:
        withdraw_form = Withdraw(request.POST)

        sender = Account.objects.get(id=request.user.id)
        reciver =  None
 
        if withdraw_form.is_valid():
            withdraw = withdraw_form.save(commit=False)
            withdraw.sender_id  = sender
            withdraw.reciver_id = reciver
            withdraw.typ = 2
            if withdraw.kwota == 0:
                    messages.info(request, 'Kwota wypłaty musi być większa niż 0')
            else:
                if getattr(sender, withdraw.waluta.lower())-withdraw.kwota >= 0:
                    setattr(sender, withdraw.waluta.lower(), getattr(sender, withdraw.waluta.lower()) - withdraw.kwota)
                    withdraw = withdraw.save()                       
                else:
                    messages.info(request, 'Brak wystarczajacej liczby środków.')

                sender.save()
                return redirect('transactions')
    return render(request, 'transactions/transactions.html', context)

def transactions_inspection_viev(request, id):
    if not request.user.is_authenticated:
        return redirect("login")
    if request.POST and 'withdraw' in request.POST:
        transactions_viev(request)
        return redirect("/saldo/")
    elif request.POST and 'transaction' in request.POST:
        transactions_viev(request)
        return redirect("/saldo/")  
    else:

        transaction = Transaction.objects.get(pk=id)
        if transaction.sender_id == request.user or transaction.reciver_id == request.user:
            transaction = transaction
        else:
            return redirect("/saldo/")
        sent_transactions = Transaction.objects.filter(Q(sender_id  = request.user.id) | Q(reciver_id = request.user.id)).order_by('-data_transakcji')
        transactions_filter = TransacionFilter(request.GET, queryset=sent_transactions)
        sent_transactions = transactions_filter
        form = NewTransaction(auto_id="NewTransaction_%s")
        withdraw_form = Withdraw()

        context = {
                'selected_transaction' : transaction,
                'sent_transactions' : sent_transactions,
                'transaction_form' : form,
                'withdraw_form' : withdraw_form,
                'transactions_filter' : transactions_filter,
            }
        return render(request, 'transactions/transactions.html', context)

def remove_transaction_order_viev(request, id):
    transaction_order=get_object_or_404(ExchangeListing, pk=id)
    if request.user == transaction_order.owner:
        transaction_order.delete()
        return redirect("/zlecenia_transakcji/")
    else:
        return redirect("/")

transactions/templates/transactions/transactions.html
{% extends 'main/base.html' %}

{%block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'transactions/transactions.css' %}">
<script src="{% static 'transactions/transactions.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock %}

{% block content %}
<div class="content">

<div class="popup" id="popup-1">
    <div class="overlay" onclick="togglePopup()">
    
    </div>
    <div class="content-popup">
    <form method="post">{% csrf_token %}
    <h1>Nowy Przelew</h1>
    <!-- Form -->
    {% for field in transaction_form %}
            
    <div class="input-box">
        <i>{{field.label}}:</i>
        <br>
        <br>
        {{field}}
    </div>

    {% for error in transaction_form.field.errors %}
        <p class="login-error">{{error}}</p>
    {% endfor %}
{% endfor %}


    {% if transaction_form.non_field_errors %}
        <div class="">
            <a>{{transaction_form.non_field_errors}}</a>
        </div>
    {% endif %}
    <input type="submit" class="buton-przelew" value="Wyslij przelew" name="transaction">
    </form>

    <div class="close-bnt" onclick="togglePopup()">&times;</div>
    </div>
</div>

<div class="popup" id="popup-2">
    <div class="overlay" onclick="togglePopup2()">
    
    </div>
    <div class="content-popup">

    <form method="post">{% csrf_token %}
    <h1>Wypłać Pieniądze</h1>
    <!-- Form -->
    {% for field in withdraw_form %}
            
    <div class="input-box">
        <i>{{field.label}}:</i>
        <br>
        <br>
        {{field}}
        {% if field.help_text %}
            <div class="help-text">{{field.help_text}}</div>
        {% endif %}
    </div>

    {% for error in withdraw_form.field.errors %}
        <p class="login-error">{{error}}</p>
    {% endfor %}
{% endfor %}


    {% if withdraw_form.non_field_errors %}
        <div class="">
            <a>{{withdraw_form.non_field_errors}}</a>
        </div>
    {% endif %}

    <input type="submit" class="buton-przelew" value="Wyplac pieniądze" name="withdraw">
    </form>

    <div class="close-bnt" onclick="togglePopup2()">&times;</div>
    </div>
</div>

    <div class="info-container">
    <div class="informacje">
        <h2>Stan konta</h2> 
        <div>
        <button onclick="togglePopup()"><i class="fas fa-plus"></i>Nowy Przelew</button>
        </div>
        <div class="flexBlock buttongroup">
        <button onclick="togglePopup2()"><i class="fas fa-money-bill-wave"></i>Wypłata z konta</button>
        </div>
        <div class="currency-wrapper">
            <div class="info-inner-container"><div class="currency-flag"><img src="{% static 'transactions/images/flags/Flag_of_China.svg' %}" class="country-flag"></div><div class="currency-ammount">Yuan:  {{request.user.cny}}</div></div>
            <div class="info-inner-container"><div class="currency-flag"><img src="{% static 'transactions/images/flags/Flag_of_Soviet_Union.svg' %}" class="country-flag"></div><div class="currency-ammount">Rubel: {{request.user.rub}}</div></div>
            <div class="info-inner-container"><div class="currency-flag"><img src="{% static 'transactions/images/flags/Flag_of_Vatican_City.svg' %}" class="country-flag"></div><div class="currency-ammount">Lira: {{request.user.lir}}</div></div>
            <div class="info-inner-container"><div class="currency-flag"><img src="{% static 'transactions/images/flags/Flag_of_Chile.svg' %}" class="country-flag"></div><div class="currency-ammount">Peso chilijskie: {{request.user.clp}}</div></div>
        </div>
    </div>
    </div>

    <div class="transactions-container">
    <h1>Transakcje</h1>
    <div>          
        <h3>Opcje filtrowania</h3> 
        <label class="switch">
            <input type="checkbox" onclick="toggleFilter();">
            <span class="slider round"></span>
        </label>
        <div class="filter-options flexBlock" id="filter-options">
        <form method="get">
            {% for field in transactions_filter.form %}
            
            <div class="input-box filter-box">
                <i>{{field.label}}:</i>
                <br>
                {{field}}
            </div>
        
            {% for error in transaction_form.field.errors %}
                <p class="login-error">{{error}}</p>
            {% endfor %}
        {% endfor %}
            <button type="submit" class="buton-przelew nowy-przelew">Filtruj</button>
        </form>
        </div>

    </div>
        <div class="transactions-wrapper">
            <div class="collumn-name" id="more-info">Informacje</div>
    
            <div class="collumn-name" id="sender">Nadawca</div>

            <div class="collumn-name" id="reciver">Odbiorca</div>
    
            <div class="collumn-name" id="ammount">Kwota</div>
    
            <div class="collumn-name" id="currency">Waluta</div>

            <div class="collumn-name" id="title">Tytuł przelewu</div>
    
            <div class="collumn-name" id="date">Data</div>
    

            {% for transaction in sent_transactions.qs %}

            <div class="more-info"><a href="{% url "inspect-transaction" transaction.transaction_id %}">Więcej Informacji</a></div>


            {% if transaction.typ == 0 %}
                {% if transaction.sender_id is not None %}
                    <div class="sender">{{transaction.sender_id}}</div>
                {% else %}
                    <div class="sender">Użytkownik usunięty</div>
                {% endif %}
            

                {% if transaction.reciver_id is not None %}
                    <div class="reciver">{{transaction.reciver_id}}</div>
                {% else %}
                    <div class="reciver">Użytkownik usunięty</div>
                {% endif %}
            {% elif transaction.typ == 1 %}
                <div class="sender">Wpłata na konto</div><div class="reciver"></div>
            {% elif transaction.typ == 2 %}
                <div class="sender">Wypłata z konta </bold></div><div class="reciver"></div>
            {% elif transaction.typ == 3 %}
                <div class="sender">Wymiana Walut</div><div class="reciver"></div>         
            {% endif %}
        

            {% if transaction.sender_id == request.user %}
                <div><a style="color: red;">-{{transaction.kwota}}</a></div>
            {% else %}
                <div><a style="color: rgb(0, 173, 0);">+{{transaction.kwota}}</a></div>
            {% endif %}


            <div class="currency"><a>{{transaction.waluta}}</a></div>
    

            {% if transaction.typ == 0 or 2 %}
                <div class="title"><a>{{transaction.title}}</a></div>
            {% else %}
                <div></div>
            {% endif %}
                <div class="date"><a>{{transaction.data_transakcji}}</a></div>
            {% endfor %}

        </div>
    </div>
</div>









{% if selected_transaction %}

<div class="popup active" id="popup-3">
<div class="overlay" onclick="togglePopup3()">

</div>
<div class="content-popup popup-inspect">
    {% if selected_transaction.typ == 0 %}
        <h2>Od:</h2>
        {% if selected_transaction.sender_id is not None %}
        <a style="color: black;">{{selected_transaction.sender_id}}</a>
        {% else %}
        <a style="color: black;">Użytkownik usunięty</a>
        {% endif %}

        <h2>Do:</h2>
        {% if selected_transaction.reciver_id is not None %}
        <a style="color: black;">{{selected_transaction.reciver_id}}</a>
        {% else %}
        <a style="color: black;">Użytkownik usunięty</a>
    {% endif %}

    {% elif selected_transaction.typ == 1 %}
    <h2 style="color: black;">Wpłata na konto</h2>
    {% elif selected_transaction.typ == 2 %}
    <h2 style="color: black;">Wypłata z konta</h2>
    {% elif selected_transaction.typ == 3 %}
    <h2 style="color: black;">Wymiana Walut</h2>    

    {% endif %}

    <h2>Kwota:</h2>
    {% if selected_transaction.sender_id == request.user %}
        <a style="color: red;">-{{selected_transaction.kwota}}</a>
    {% else %}
        <a style="color: rgb(0, 173, 0);">+{{selected_transaction.kwota}}</a>
    {% endif %}
    <a style="color: black;">{{selected_transaction.waluta}}</a>


    {% if selected_transaction.typ == 0 %}
    <h2>Tytuł: </h2>
    <a style="color: black;">{{selected_transaction.title}}</a>
    {% endif %}
    <h2>Data:</h2>
    <a style="color: black;">{{selected_transaction.data_transakcji}}</a>
    <div class="close-bnt" onclick="togglePopup3()">&times;</div>
    </div>
</div>

</div>
{% endif %}

<script>
$(document).ready(function() {
    $('#NewTransaction_waluta').select2();
    $('#id_waluta2').select2();
    $('#id_waluta').select2();
    $('#id_daterange').select2();
});
</script>

<script>
$(function(){         
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){ 
    message_ele.style.display = "none"; 
    }, 3000);
});

$(function(){         
    $('.innerBar').animate({ width: "0%" }, 3000);
});
</script>

<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script>
    $(document).ready(function () {
        $('#NewTransaction_reciver_id').select2({
            ajax: {
                url: '{% url 'transactions' %}',
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.username};
                        })
                    };
                }
            },
            minimumInputLength: 3
        });
        
    });
</script>

<script>
    $(document).ready(function () {
        $('#id_sender_id').select2({
            ajax: {
                url: '{% url 'transactions' %}',
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.username};
                        })
                    };
                }
            },
            minimumInputLength: 3
        });
        
    });
</script>
<script>
$(document).ready(function () {
    $('#id_reciver_id').select2({
        ajax: {
            url: '{% url 'transactions' %}',
            dataType: 'json',
            processResults: function (data) {
                return {
                    results: $.map(data, function (item) {
                        return {id: item.id, text: item.username};
                    })
                };
            }
        },
        minimumInputLength: 3
    });
    
});
</script>
{% endblock %}