django_bank/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import (
    registration_viev,
    logout_viev,
    login_viev,
    account_viev,
    change_password,
)

from transactions.views import (
    transactions_viev,
    transactions_inspection_viev,
)

from exchange.views import (
    exchange_viev,
    remove_lising_viev,
    exchange_money_viev,
)

from admindashboard.views import (
    admindashboard_viev,
    admindashboard_inspection_viev,
    admindashboard_mark_transaction,
)
from transaction_order.views import (
    transaction_order_viev,
    remove_transaction_order_viev,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("main.urls")),
    path('register/', registration_viev, name="register"),
    path('logout/', logout_viev, name="logout"),
    path('login/', login_viev, name="login"),

    path('account/', account_viev, name="account"),
    path('account/change_password', change_password, name="change_password"),

    path('saldo/', transactions_viev, name="transactions"),
    path('saldo/<int:id>', transactions_inspection_viev, name="inspect-transaction"),

    path('wymiana_walut/', exchange_viev, name="exchange"),
    path('removelisting/<int:id>', remove_lising_viev, name="remove-listing"),
    path('wymiana_walut/<int:id>', exchange_money_viev, name="exchange-money"),
    
    path('admindashboard/', admindashboard_viev, name="admindashboard"),
    path('admindashboard/inspect/<int:id>', admindashboard_inspection_viev, name="admin-inspect-transaction"),
    path('admindashboard/mark/<int:id>', admindashboard_mark_transaction, name="admin-mark-transaction"),

    path('zlecenia_transakcji/', transaction_order_viev, name="zlecenia_transakcji"),
    path('zlecenia_transakcji/<int:id>', remove_transaction_order_viev, name="remove_zlecenia_transakcji"),
    
    path('api/', include('transactions_api.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home")
]

exchange/models.py
from django.db import models
from account.models import Account

class ExchangeListing(models.Model):
    WALUTY = (
        ('CNY', 'Yuan'),
        ('RUB', 'Rubel'),
        ('LIR', 'Lira'),
        ('CLP', 'Peso chilijskie'),
    )

    owner               = models.ForeignKey(Account, blank=True, null=True, on_delete=models.CASCADE)
    exchange_from       = models.CharField(verbose_name="Wymiana z", max_length=32, unique=False, choices=WALUTY)
    exchange_to         = models.CharField(verbose_name="Wymiana na", max_length=32, unique=False, choices=WALUTY)
    amount_owned        = models.PositiveIntegerField(verbose_name="Kwota1", blank=False, default=0)
    amount_wanted       = models.PositiveIntegerField(verbose_name="Kwota2", blank=False, default=0)
    ratio_from          = models.PositiveIntegerField(verbose_name="Ratio Góra", blank=False, default=1)
    ratio_to            = models.PositiveIntegerField(verbose_name="Ratio Dół", blank=False, default=1)
    is_fixed            = models.BooleanField(default=False)




    def __str__(self):
        return str(self.id)

exchange/forms.py
from django import forms
from exchange.models import ExchangeListing

class NewExchaneListing(forms.ModelForm):
    
    class Meta:
        model = ExchangeListing
        fields = ['exchange_from', 'amount_owned', 'exchange_to', 'amount_wanted']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['exchange_from'].label  = "Waluta z której chcesz wymienić"
        self.fields['exchange_to'].label    = "Waluta na którą chcesz wymienić"
        self.fields['amount_owned'].label = "Kwota, która chcemy wymienić"
        self.fields['amount_wanted'].label = "Kwota, która otrzymasz"


class ExchangeMoneyForm(forms.Form):
    amount_exchanged = forms.IntegerField(min_value=0, required=True)
    amount_recived = forms.IntegerField(min_value=1, required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['amount_recived'].widget.attrs['readonly'] = True
        self.fields['amount_exchanged'].label = "Kwota, która chcesz wymienić"
        self.fields['amount_recived'].label = "Kwota, która otrzymasz"

exchange/views.py
from django.shortcuts import get_object_or_404, render, redirect

from exchange.forms import NewExchaneListing, ExchangeMoneyForm
from exchange.models import ExchangeListing
from exchange.filters import ExchangeListingFilter
from exchange.nwd import NWD

from transactions.models import Transaction

from django.contrib import messages

def exchange_viev(request):
    if not request.user.is_authenticated:
        return redirect("login")
    exchange_listings = ExchangeListing.objects.all()
    exchangelisting_filter = ExchangeListingFilter(request.GET, queryset=exchange_listings)
    exchange_listings = exchangelisting_filter

    exchange_form = NewExchaneListing(auto_id="NewExchaneListing_%s")
    context = {
        'exchange_listings' : exchange_listings,
        'exchange_form' : exchange_form,
        'exchangelisting_filter' : exchangelisting_filter,
    }

    if request.POST and 'new-exchange-listing' in request.POST:
        
        exchange_form = NewExchaneListing(request.POST)
        if exchange_form.is_valid():
            exchange_listing = exchange_form.save(commit=False)
            exchange_listing.owner = request.user

            exchange_creator = request.user

            if exchange_listing.exchange_from == exchange_listing.exchange_to:
                messages.info(request, 'Nie możesz wymienić waluty na ta sama')
            elif exchange_listing.amount_owned == 0 or exchange_listing.amount_wanted == 0:
                messages.info(request, 'Wartość musi być wyższa niż zero')
            else:
                nwd = NWD(exchange_listing.amount_owned, exchange_listing.amount_wanted)
                exchange_listing.ratio_from = (exchange_listing.amount_owned/nwd)
                exchange_listing.ratio_to = (exchange_listing.amount_wanted/nwd)

                if getattr(exchange_creator, exchange_listing.exchange_from.lower()) - exchange_listing.amount_owned >= 0:
                    setattr(exchange_creator, exchange_listing.exchange_from.lower(), getattr(exchange_creator, exchange_listing.exchange_from.lower()) - exchange_listing.amount_owned)
                    exchange_creator.save()
                    exchange_listing.save()
                    messages.info(request, 'Pomyślnie umieszczono oferte wymiany')
                else:
                    messages.info(request, 'Brak wystarczajacej liczby środków.')
            return redirect('exchange')
    return render(request, 'exchange/exchange.html', context)




def remove_lising_viev(request, id):
    exchange_listing=get_object_or_404(ExchangeListing, pk=id)
    if request.user == exchange_listing.owner:
        exchange_creator = exchange_listing.owner

        setattr(exchange_creator, exchange_listing.exchange_from.lower(), getattr(exchange_creator, exchange_listing.exchange_from.lower()) + exchange_listing.amount_owned)  

        exchange_creator.save()
        exchange_listing.delete()
        return redirect("/wymiana_walut/")
    else:
        return redirect("/")

def exchange_money_viev(request, id):
    if not request.user.is_authenticated:
        return redirect("login")
    exchange_listings = ExchangeListing.objects.all()
    exchange_money_form = ExchangeMoneyForm()

    exchange_listings = ExchangeListing.objects.all()
    exchangelisting_filter = ExchangeListingFilter(request.GET, queryset=exchange_listings)
    exchange_listings = exchangelisting_filter

    exchange_form = NewExchaneListing(auto_id="NewExchaneListing_%s")

    selected_exchange_listing = get_object_or_404(ExchangeListing, pk=id)

    context = {
        'exchange_listings' : exchange_listings,
        'exchange_form' : exchange_form,
        'exchange_money_form' : exchange_money_form,
        'exchangelisting_filter' : exchangelisting_filter,
        'selected_exchange_listing' : selected_exchange_listing,
    }
    
    if request.POST and 'new-exchange-listing' in request.POST:
        exchange_viev(request)
        return redirect("/wymiana_walut/")
    elif request.POST and 'exchange-money' in request.POST:
        exchange_money_form = ExchangeMoneyForm(request.POST)
        if exchange_money_form.is_valid():
            cd = exchange_money_form.cleaned_data
            amount_exchanged = cd.get('amount_exchanged')
            amount_recived = cd.get('amount_recived')

            if selected_exchange_listing.amount_wanted - amount_exchanged >= 0:
                if getattr(request.user, selected_exchange_listing.exchange_to.lower()) - amount_exchanged >= 0:
                    setattr(request.user, selected_exchange_listing.exchange_to.lower(), getattr(request.user, selected_exchange_listing.exchange_to.lower()) - amount_exchanged)
                    setattr(request.user, selected_exchange_listing.exchange_from.lower(), getattr(request.user, selected_exchange_listing.exchange_from.lower()) + amount_recived)
                    setattr(selected_exchange_listing.owner, selected_exchange_listing.exchange_to.lower(), getattr(selected_exchange_listing.owner, selected_exchange_listing.exchange_to.lower()) + amount_exchanged)
                else:
                    messages.info(request, 'Brak wystarczajacej liczby środków.')


                selected_exchange_listing.amount_wanted -= amount_exchanged
                selected_exchange_listing.amount_owned -= amount_recived

                amount_exchanged_transaction = Transaction(sender_id=selected_exchange_listing.owner, reciver_id=request.user, waluta=selected_exchange_listing.exchange_from, kwota=amount_recived, typ=3, title="")
                amount_exchanged_transaction.save()
                amount_recived_transaction = Transaction(sender_id=request.user, reciver_id=selected_exchange_listing.owner, waluta=selected_exchange_listing.exchange_to, kwota=amount_exchanged, typ=3, title="") 
                amount_recived_transaction.save()

                request.user.save()
                selected_exchange_listing.owner.save()
                selected_exchange_listing.save()

                if selected_exchange_listing.amount_wanted == 0 and not selected_exchange_listing.is_fixed or selected_exchange_listing.amount_wanted == 0 and not selected_exchange_listing.is_fixed:
                    selected_exchange_listing.delete()

                succes_msg = str('Pomyślnie wymieniono '+str(amount_exchanged)+str(selected_exchange_listing.exchange_to)+' na '+str(amount_recived)+str(selected_exchange_listing.exchange_from))
                messages.info(request, succes_msg)

        return redirect("/wymiana_walut/")

    return render(request, 'exchange/exchange.html', context)

exchange/templates/exchange/exchange.html
{% extends 'main/base.html' %}

{%block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'transactions/transactions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'exchange/exchange.css' %}">
<script src="{% static 'exchange/exchange.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

{% endblock %}

{% block content %}
    <div class="popup" id="popup-1">
    <div class="overlay" onclick="togglePopup()">
        
    </div>
    <div class="content-popup">
        <form method="post">{% csrf_token %}
        <h1>Wymień waluty</h1>
        {% for field in exchange_form %}
                
        <div class="input-box">
            <i>{{field.label}}:</i>
            <br>
            <br>
            {{field}}
        </div>
    
        {% for error in exchange_form.field.errors %}
            <p class="login-error">{{error}}</p>
        {% endfor %}
        {% endfor %}
    
    
        {% if exchange_form.non_field_errors %}
            <div class="">
                <a>{{exchange_form.non_field_errors}}</a>
            </div>
        {% endif %}
        <input type="submit" class="buton-przelew" value="Wymień" name="new-exchange-listing">
        </form>
    
        <div class="close-bnt" onclick="togglePopup()">&times;</div>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>

<div class="content">
        <div class="exchange-info-container">
            <h2>Wymień waluty</h2> <button onclick="togglePopup()" class="buton-przelew button-oferawymiany"><i class="fas fa-plus"></i>Nowa Oferta Wymiany Walut</button>

            <form method="get">
                {% for field in exchangelisting_filter.form %}
                
                <div class="input-box filter-box">
                    <i>{{field.label}}:</i>
                    <br>
                    {{field}}
                </div>
            
                {% for error in transaction_form.field.errors %}
                    <p class="login-error">{{error}}</p>
                {% endfor %}
                {% endfor %}
                <button type="submit" class="buton-przelew nowy-przelew">Filtruj</button>
            </form>
        </div>

    {% for exchange_listing in exchange_listings.qs %}
    <div class="exchange-listing-container">
        <h2>Wymień</h2>
        <h3>{{exchange_listing.amount_wanted}} {{exchange_listing.exchange_to}} Na {{exchange_listing.amount_owned}} {{exchange_listing.exchange_from}}</h3>
        <h3>Ratio:</h3>
        <h4>{{exchange_listing.ratio_to}} {{exchange_listing.exchange_to}} : {{exchange_listing.ratio_from}} {{exchange_listing.exchange_from}}</h4>
        <h4 style="color: gray">Oferta od: {{exchange_listing.owner}}</h4>
        <!-- <h4 style="color: gray">Id: {{exchange_listing.id}}</h4> -->

        
        {% if exchange_listing.owner == request.user %}
        <a href="{% url "remove-listing" exchange_listing.id %}" class="link-button button-del">Usuń ofertę wymiany</a>
        {% else %}
        <a href="{% url "exchange-money" exchange_listing.id %}" class="link-button">Wymień</a>
        {% endif %}
    </div>
    {% endfor %}

    {%if selected_exchange_listing %}

    <div class="popup active" id="popup-2">
        <div class="overlay" onclick="togglePopup1()">

        </div>
        <div class="content-popup">
        <!-- <h4>{{selected_exchange_listing.id}}</h4> -->
        <form method="post">{% csrf_token %}

            {% for field in exchange_money_form %}
                
            <div class="input-box">
                <i>{{field.label}}:</i>
                <br>
                <br>
                {{field}}
            </div>
        
            {% for error in exchange_money_form.field.errors %}
                <p class="login-error">{{error}}</p>
            {% endfor %}
            {% endfor %}            
        <input type="submit" value="Wymień Pieniądze" name="exchange-money">
        </form>
        <script>
            document.getElementById("id_amount_exchanged").step = Number({{selected_exchange_listing.ratio_to}})
            document.getElementById("id_amount_exchanged").max = Number({{selected_exchange_listing.amount_wanted}}) 
            document.getElementById("id_amount_exchanged").placeholder = "Kwota którą chcesz wymienić w " + "{{selected_exchange_listing.exchange_to}}"
            document.getElementById("id_amount_recived").placeholder = "Kwota którą dostaniesz w " + "{{selected_exchange_listing.exchange_from}}"
        </script>

        <script>
            document.getElementById("id_amount_exchanged").oninput = () => {
            document.getElementById("id_amount_recived").value = ((document.getElementById("id_amount_exchanged").value)/{{selected_exchange_listing.ratio_to}}) * {{selected_exchange_listing.ratio_from}}
            }
        </script>

        <div class="close-bnt" onclick="togglePopup1()">&times;</div>
        </div>
    </div>
    {%endif%}
    </div>
</div>
<script>
$(document).ready(function() {
    $('#NewExchaneListing_exchange_from').select2();
    $('#NewExchaneListing_exchange_to').select2();
    $('#id_exchange_from').select2();
    $('#id_exchange_to').select2();
});
</script>

<script>
$(function(){         
    var message_ele = document.getElementById("message_container");
    setTimeout(function(){ 
    message_ele.style.display = "none"; 
    }, 3000);
});

$(function(){         
    $('.innerBar').animate({ width: "0%" }, 3000);
});
</script>

{% endblock %}