django_bank/urls.py
from django.contrib import admin
from django.urls import path, include

from account.views import (
    registration_viev,
    logout_viev,
    login_viev,
    account_viev,
    change_password,
)

from transactions.views import (
    transactions_viev,
    transactions_inspection_viev,
)

from exchange.views import (
    exchange_viev,
    remove_lising_viev,
    exchange_money_viev,
)

from admindashboard.views import (
    admindashboard_viev,
    admindashboard_inspection_viev,
    admindashboard_mark_transaction,
)
from transaction_order.views import (
    transaction_order_viev,
    remove_transaction_order_viev,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include("main.urls")),
    path('register/', registration_viev, name="register"),
    path('logout/', logout_viev, name="logout"),
    path('login/', login_viev, name="login"),

    path('account/', account_viev, name="account"),
    path('account/change_password', change_password, name="change_password"),

    path('saldo/', transactions_viev, name="transactions"),
    path('saldo/<int:id>', transactions_inspection_viev, name="inspect-transaction"),

    path('wymiana_walut/', exchange_viev, name="exchange"),
    path('removelisting/<int:id>', remove_lising_viev, name="remove-listing"),
    path('wymiana_walut/<int:id>', exchange_money_viev, name="exchange-money"),
    
    path('admindashboard/', admindashboard_viev, name="admindashboard"),
    path('admindashboard/inspect/<int:id>', admindashboard_inspection_viev, name="admin-inspect-transaction"),
    path('admindashboard/mark/<int:id>', admindashboard_mark_transaction, name="admin-mark-transaction"),

    path('zlecenia_transakcji/', transaction_order_viev, name="zlecenia_transakcji"),
    path('zlecenia_transakcji/<int:id>', remove_transaction_order_viev, name="remove_zlecenia_transakcji"),
    
    path('api/', include('transactions_api.urls')),
]

main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.home, name="home")
]

transaction_order/models.py
from django.db import models
from account.models import Account
from django.utils import timezone
class TransactionOrder(models.Model):
    WALUTY = (
        ('CNY', 'Yuan'),
        ('RUB', 'Rubel'),
        ('LIR', 'Lira'),
        ('CLP', 'Peso chilijskie'),
    )

    TIME_DIFFERENCES = (
        (1, 'Codziennie'),
        (7, 'Co siedem dni'),
        (30, 'Raz na 30 dni'),
        (90, 'Raz na 90 dni'),
        (365, 'Raz na 365 dni'),
    )


    transaction_order_id    = models.BigAutoField(verbose_name="Id Zlecenia Tranzakcji", primary_key=True)
    sender_fk               = models.ForeignKey(Account, blank=False, on_delete=models.CASCADE, related_name='NadawcaZleceniaTranzakcji', verbose_name="Nadawca")
    reciver_fk              = models.ForeignKey(Account, blank=False, on_delete=models.CASCADE, related_name='OdbiorcaZleceniaTranzakcji', verbose_name="Odbiorca")
    amount                  = models.PositiveIntegerField(verbose_name="Kwota", blank=False, default=0)
    waluta                  = models.CharField(verbose_name="Waluta", max_length=32, unique=False, choices=WALUTY)
    last_transaction        = models.DateTimeField(verbose_name='Ostatnia tranzakcja', auto_now_add=True)
    transaction_delay       = models.IntegerField(unique=False, blank=False, choices=TIME_DIFFERENCES, verbose_name="Cykliczność")
    title                   = models.CharField(verbose_name="Tytuł przelewu", max_length=100, unique=False, default="Tytuł Przelewu")

    def save(self, *args, **kwargs):
        self.last_transaction = timezone.now()
        super().save(*args, **kwargs)

    def __str__(self):
        return str(self.transaction_order_id)

transaction_order/forms.py
from django import forms
from transaction_order.models import TransactionOrder
from account.models import Account




class NewTransactionOrder(forms.ModelForm):
    
    class Meta:
            model = TransactionOrder
            fields = ['title', 'reciver_fk', 'amount', 'waluta', 'transaction_delay']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['reciver_fk'].label = "Nazwa odbiorcy"
        self.fields['reciver_fk'].queryset = Account.objects.none()

        if 'reciver_fk' in self.data:
            self.fields['reciver_fk'].queryset = Account.objects.all()

        elif self.instance.pk:
            self.fields['reciver_fk'].queryset = Account.objects.all().filter(pk=self.instance.reciver_fk.pk)

transaction_order/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from account.models import Account
from django.db.models import Q

from transaction_order.models import TransactionOrder
from transaction_order.forms import NewTransactionOrder
from transaction_order.filters import TransactionOrderFilter

from django.contrib import messages


def transaction_order_viev(request):
    

    if not request.user.is_authenticated:
        return redirect("login")

    transaction_orders = TransactionOrder.objects.filter(Q(sender_fk  = request.user.id)).order_by('-transaction_delay')
    transaction_orders_filter = TransactionOrderFilter(request.GET, queryset=transaction_orders)
    transaction_orders = transaction_orders_filter
    transaction_order_form = NewTransactionOrder(auto_id="NewTransactionOrder_%s")

    
    context = {
            'transaction_orders' : transaction_orders,
            'transaction_order_form' : transaction_order_form,
            'transaction_orders_filter' : transaction_orders_filter,
        }
    
    # Wyszukiwanie konta 
    is_ajax = request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
    if is_ajax:
        term = request.GET['q']
        reciver_fk = Account.objects.all().filter(username__icontains=term)
        return JsonResponse(list(reciver_fk.values()), safe=False)    

    # Zlecenie tranzakcji
    if request.POST and 'transaction' in request.POST:
        transaction_order_form = NewTransactionOrder(request.POST)
        if transaction_order_form.is_valid():
            trans = transaction_order_form.save(commit=False)
            trans.sender_fk = request.user

            sender = Account.objects.get(id=request.user.id)
            reciver = Account.objects.get(id=trans.reciver_fk.id)

            if sender == reciver:
                messages.info(request, 'Nie możesz stworzyć zlecenia do samego siebie.')
            else:
                if trans.amount == 0:
                    messages.info(request, 'Kwota przelewu musi być większa niż 0')
                else:
                    trans = trans.save()
                    return redirect('zlecenia_transakcji')
    return render(request, 'transaction_order/transaction_order.html', context)


def remove_transaction_order_viev(request, id):
    transaction_order=get_object_or_404(TransactionOrder, pk=id)
    if request.user == transaction_order.sender_fk:
        transaction_order.delete()
        return redirect("/zlecenia_transakcji/")
    else:
        return redirect("/")

transaction_order/templates/transaction_order/transaction_order.html
{% extends 'main/base.html' %}

{%block head %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'main/base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'transactions/transactions.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'transaction_order/transaction_order.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css" rel="stylesheet"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"></script>
<script src="{% static 'transaction_order/transaction_order.js' %}"></script>
<script src="{% static 'transactions/transactions.js' %}"></script>
{% endblock %}

{% block content %}
<div class="content">
<div class="info-container">
<div class="informacje">
<form method="post">{% csrf_token %}
    <h1>Nowe zlecenie transakcji</h1>
    <!-- Form -->
    {% for field in transaction_order_form %}
            
    <div class="input-box">
        <i>{{field.label}}:</i>
        <br>
        <br>
        {{field}}
    </div>

        {% for error in transaction_form.field.errors %}
            <p class="login-error">{{error}}</p>
        {% endfor %}
    {% endfor %}


    {% if transaction_form.non_field_errors %}
        <div class="">
            <a>{{transaction_form.non_field_errors}}</a>
        </div>
    {% endif %}
    <input type="submit" class="buton-przelew buton-zlecenie" value="Nowe zlecenie transakcji" name="transaction">
    </form>

    <!-- Dropdown jQuerry -->
  <script>
      $(document).ready(function () {
          $('#NewTransactionOrder_reciver_fk').select2({
              ajax: {
                  url: '{% url 'zlecenia_transakcji' %}',
                  dataType: 'json',
                  processResults: function (data) {
                      return {
                          results: $.map(data, function (item) {
                              return {id: item.id, text: item.username};
                          })
                      };
                  }
              },
              minimumInputLength: 3
          });
          
      });
  </script>

<script>
    $(document).ready(function () {
        $('#id_reciver_fk').select2({
            ajax: {
                url: '{% url 'zlecenia_transakcji' %}',
                dataType: 'json',
                processResults: function (data) {
                    return {
                        results: $.map(data, function (item) {
                            return {id: item.id, text: item.username};
                        })
                    };
                }
            },
            minimumInputLength: 3
        });
        
    });
</script>
</div>
</div>

<div class="transaction-orders-container">
    <h1>Twoje zlecenia transakcji</h1>
    <div>          
      <h3>Opcje filtrowania</h3> 
      <label class="switch">
        <input type="checkbox" onclick="toggleFilter();">
        <span class="slider round"></span>
      </label>


      <div class="filter-options flexBlock" id="filter-options">
        <form method="get">
          {% for field in transaction_orders_filter.form %}
            
          <div class="input-box filter-box">
              <i>{{field.label}}:</i>
              <br>
              {{field}}
          </div>
      
          {% for error in transaction_form.field.errors %}
              <p class="login-error">{{error}}</p>
          {% endfor %}
      {% endfor %}
          <button type="submit" class="buton-przelew nowy-przelew">Filtruj</button>
        </form>
      </div>

    <div class="transaction-orders-wrapper">
        <div class="collumn-name" id="more-info">Odbiorca</div>

        <div class="collumn-name" id="ammount">Kwota</div>

        <div class="collumn-name" id="currency">Waluta</div>

        <div class="collumn-name" id="delay">Odstęp czasowy</div>

        <div class="collumn-name" id="title">Tytuł przelewu</div>

        <div class="collumn-name" id="date">Ostatnia tranzakcja</div>

        <div class="collumn-name"></div>

        {% for transaction_order in transaction_orders.qs %}
            <div>{{transaction_order.reciver_fk}}</div>
            <div>{{transaction_order.amount}}</div>
            <div class="currency">{{transaction_order.waluta}}</div>
            <div class="delay">{{transaction_order.transaction_delay}} dni</div>
            <div class="title">{{transaction_order.title}}</div>
            <div class="date">{{transaction_order.last_transaction}}</div>
            <div class="del"><a href="{% url "remove_zlecenia_transakcji" transaction_order.transaction_order_id %}" class="link-button button-del">Usuń zlecenie transakcji</a></div>
        {% endfor %}
    </div>

    </div>
</div>
</div>

{% if messages %}
    {% for message in messages %}
        <div class="message" id="message_container"      >
            <p>{{ message }}</p>
            <a href="" class="del-msg">
                &times;
            </a>
            <div class="outerContainer">
                <div class="innerBar"></div>
            </div>
        </div>
    {% endfor %}
{% endif %}
{% endblock %}